/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout.index'
import { Route as LayoutAboutImport } from './routes/_layout.about'
import { Route as LayoutAuthImport } from './routes/_layout._auth'
import { Route as LayoutAuthDashboardUsuarioImport } from './routes/_layout._auth/dashboard/_usuario'
import { Route as LayoutAuthDashboardUsuarioIndexImport } from './routes/_layout._auth/dashboard/_usuario/index'
import { Route as LayoutAuthDashboardUsuarioEditImport } from './routes/_layout._auth/dashboard/_usuario/edit'

// Create Virtual Routes

const LayoutAuthDashboardImport = createFileRoute('/_layout/_auth/dashboard')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthDashboardRoute = LayoutAuthDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthDashboardUsuarioRoute = LayoutAuthDashboardUsuarioImport.update(
  {
    id: '/_usuario',
    getParentRoute: () => LayoutAuthDashboardRoute,
  } as any,
)

const LayoutAuthDashboardUsuarioIndexRoute =
  LayoutAuthDashboardUsuarioIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthDashboardUsuarioRoute,
  } as any)

const LayoutAuthDashboardUsuarioEditRoute =
  LayoutAuthDashboardUsuarioEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutAuthDashboardUsuarioRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_auth/dashboard': {
      id: '/_layout/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthDashboardImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_auth/dashboard/_usuario': {
      id: '/_layout/_auth/dashboard/_usuario'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthDashboardUsuarioImport
      parentRoute: typeof LayoutAuthDashboardRoute
    }
    '/_layout/_auth/dashboard/_usuario/edit': {
      id: '/_layout/_auth/dashboard/_usuario/edit'
      path: '/edit'
      fullPath: '/dashboard/edit'
      preLoaderRoute: typeof LayoutAuthDashboardUsuarioEditImport
      parentRoute: typeof LayoutAuthDashboardUsuarioImport
    }
    '/_layout/_auth/dashboard/_usuario/': {
      id: '/_layout/_auth/dashboard/_usuario/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof LayoutAuthDashboardUsuarioIndexImport
      parentRoute: typeof LayoutAuthDashboardUsuarioImport
    }
  }
}

// Create and export the route tree

interface LayoutAuthDashboardUsuarioRouteChildren {
  LayoutAuthDashboardUsuarioEditRoute: typeof LayoutAuthDashboardUsuarioEditRoute
  LayoutAuthDashboardUsuarioIndexRoute: typeof LayoutAuthDashboardUsuarioIndexRoute
}

const LayoutAuthDashboardUsuarioRouteChildren: LayoutAuthDashboardUsuarioRouteChildren =
  {
    LayoutAuthDashboardUsuarioEditRoute: LayoutAuthDashboardUsuarioEditRoute,
    LayoutAuthDashboardUsuarioIndexRoute: LayoutAuthDashboardUsuarioIndexRoute,
  }

const LayoutAuthDashboardUsuarioRouteWithChildren =
  LayoutAuthDashboardUsuarioRoute._addFileChildren(
    LayoutAuthDashboardUsuarioRouteChildren,
  )

interface LayoutAuthDashboardRouteChildren {
  LayoutAuthDashboardUsuarioRoute: typeof LayoutAuthDashboardUsuarioRouteWithChildren
}

const LayoutAuthDashboardRouteChildren: LayoutAuthDashboardRouteChildren = {
  LayoutAuthDashboardUsuarioRoute: LayoutAuthDashboardUsuarioRouteWithChildren,
}

const LayoutAuthDashboardRouteWithChildren =
  LayoutAuthDashboardRoute._addFileChildren(LayoutAuthDashboardRouteChildren)

interface LayoutAuthRouteChildren {
  LayoutAuthDashboardRoute: typeof LayoutAuthDashboardRouteWithChildren
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthDashboardRoute: LayoutAuthDashboardRouteWithChildren,
}

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutAuthRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/dashboard': typeof LayoutAuthDashboardUsuarioRouteWithChildren
  '/dashboard/edit': typeof LayoutAuthDashboardUsuarioEditRoute
  '/dashboard/': typeof LayoutAuthDashboardUsuarioIndexRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutAuthRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/dashboard': typeof LayoutAuthDashboardUsuarioIndexRoute
  '/dashboard/edit': typeof LayoutAuthDashboardUsuarioEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_auth/dashboard': typeof LayoutAuthDashboardRouteWithChildren
  '/_layout/_auth/dashboard/_usuario': typeof LayoutAuthDashboardUsuarioRouteWithChildren
  '/_layout/_auth/dashboard/_usuario/edit': typeof LayoutAuthDashboardUsuarioEditRoute
  '/_layout/_auth/dashboard/_usuario/': typeof LayoutAuthDashboardUsuarioIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/'
    | '/dashboard'
    | '/dashboard/edit'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/about' | '/' | '/dashboard' | '/dashboard/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_auth'
    | '/_layout/about'
    | '/_layout/'
    | '/_layout/_auth/dashboard'
    | '/_layout/_auth/dashboard/_usuario'
    | '/_layout/_auth/dashboard/_usuario/edit'
    | '/_layout/_auth/dashboard/_usuario/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_auth",
        "/_layout/about",
        "/_layout/"
      ]
    },
    "/_layout/_auth": {
      "filePath": "_layout._auth.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_auth/dashboard"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout.about.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_auth/dashboard": {
      "filePath": "_layout._auth/dashboard",
      "parent": "/_layout/_auth",
      "children": [
        "/_layout/_auth/dashboard/_usuario"
      ]
    },
    "/_layout/_auth/dashboard/_usuario": {
      "filePath": "_layout._auth/dashboard/_usuario.tsx",
      "parent": "/_layout/_auth/dashboard",
      "children": [
        "/_layout/_auth/dashboard/_usuario/edit",
        "/_layout/_auth/dashboard/_usuario/"
      ]
    },
    "/_layout/_auth/dashboard/_usuario/edit": {
      "filePath": "_layout._auth/dashboard/_usuario/edit.tsx",
      "parent": "/_layout/_auth/dashboard/_usuario"
    },
    "/_layout/_auth/dashboard/_usuario/": {
      "filePath": "_layout._auth/dashboard/_usuario/index.tsx",
      "parent": "/_layout/_auth/dashboard/_usuario"
    }
  }
}
ROUTE_MANIFEST_END */
