/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout.index'
import { Route as LayoutAboutImport } from './routes/_layout.about'
import { Route as LayoutAuthImport } from './routes/_layout._auth'
import { Route as LayoutAuthDashboardIndexImport } from './routes/_layout._auth/dashboard/index'
import { Route as LayoutAuthProfileUsuarioImport } from './routes/_layout._auth/profile/_usuario'
import { Route as LayoutAuthProfileUsuarioIndexImport } from './routes/_layout._auth/profile/_usuario/index'
import { Route as LayoutAuthProfileUsuarioEditImport } from './routes/_layout._auth/profile/_usuario/edit'

// Create Virtual Routes

const LayoutAuthProfileImport = createFileRoute('/_layout/_auth/profile')()

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAboutRoute = LayoutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthRoute = LayoutAuthImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAuthProfileRoute = LayoutAuthProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthDashboardIndexRoute = LayoutAuthDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutAuthRoute,
} as any)

const LayoutAuthProfileUsuarioRoute = LayoutAuthProfileUsuarioImport.update({
  id: '/_usuario',
  getParentRoute: () => LayoutAuthProfileRoute,
} as any)

const LayoutAuthProfileUsuarioIndexRoute =
  LayoutAuthProfileUsuarioIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthProfileUsuarioRoute,
  } as any)

const LayoutAuthProfileUsuarioEditRoute =
  LayoutAuthProfileUsuarioEditImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutAuthProfileUsuarioRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/_auth/profile': {
      id: '/_layout/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthProfileImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_auth/profile/_usuario': {
      id: '/_layout/_auth/profile/_usuario'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthProfileUsuarioImport
      parentRoute: typeof LayoutAuthProfileRoute
    }
    '/_layout/_auth/dashboard/': {
      id: '/_layout/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutAuthDashboardIndexImport
      parentRoute: typeof LayoutAuthImport
    }
    '/_layout/_auth/profile/_usuario/edit': {
      id: '/_layout/_auth/profile/_usuario/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof LayoutAuthProfileUsuarioEditImport
      parentRoute: typeof LayoutAuthProfileUsuarioImport
    }
    '/_layout/_auth/profile/_usuario/': {
      id: '/_layout/_auth/profile/_usuario/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof LayoutAuthProfileUsuarioIndexImport
      parentRoute: typeof LayoutAuthProfileUsuarioImport
    }
  }
}

// Create and export the route tree

interface LayoutAuthProfileUsuarioRouteChildren {
  LayoutAuthProfileUsuarioEditRoute: typeof LayoutAuthProfileUsuarioEditRoute
  LayoutAuthProfileUsuarioIndexRoute: typeof LayoutAuthProfileUsuarioIndexRoute
}

const LayoutAuthProfileUsuarioRouteChildren: LayoutAuthProfileUsuarioRouteChildren =
  {
    LayoutAuthProfileUsuarioEditRoute: LayoutAuthProfileUsuarioEditRoute,
    LayoutAuthProfileUsuarioIndexRoute: LayoutAuthProfileUsuarioIndexRoute,
  }

const LayoutAuthProfileUsuarioRouteWithChildren =
  LayoutAuthProfileUsuarioRoute._addFileChildren(
    LayoutAuthProfileUsuarioRouteChildren,
  )

interface LayoutAuthProfileRouteChildren {
  LayoutAuthProfileUsuarioRoute: typeof LayoutAuthProfileUsuarioRouteWithChildren
}

const LayoutAuthProfileRouteChildren: LayoutAuthProfileRouteChildren = {
  LayoutAuthProfileUsuarioRoute: LayoutAuthProfileUsuarioRouteWithChildren,
}

const LayoutAuthProfileRouteWithChildren =
  LayoutAuthProfileRoute._addFileChildren(LayoutAuthProfileRouteChildren)

interface LayoutAuthRouteChildren {
  LayoutAuthProfileRoute: typeof LayoutAuthProfileRouteWithChildren
  LayoutAuthDashboardIndexRoute: typeof LayoutAuthDashboardIndexRoute
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthProfileRoute: LayoutAuthProfileRouteWithChildren,
  LayoutAuthDashboardIndexRoute: LayoutAuthDashboardIndexRoute,
}

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutAuthRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/profile': typeof LayoutAuthProfileUsuarioRouteWithChildren
  '/dashboard': typeof LayoutAuthDashboardIndexRoute
  '/profile/edit': typeof LayoutAuthProfileUsuarioEditRoute
  '/profile/': typeof LayoutAuthProfileUsuarioIndexRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutAuthRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/': typeof LayoutIndexRoute
  '/profile': typeof LayoutAuthProfileUsuarioIndexRoute
  '/dashboard': typeof LayoutAuthDashboardIndexRoute
  '/profile/edit': typeof LayoutAuthProfileUsuarioEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_auth/profile': typeof LayoutAuthProfileRouteWithChildren
  '/_layout/_auth/profile/_usuario': typeof LayoutAuthProfileUsuarioRouteWithChildren
  '/_layout/_auth/dashboard/': typeof LayoutAuthDashboardIndexRoute
  '/_layout/_auth/profile/_usuario/edit': typeof LayoutAuthProfileUsuarioEditRoute
  '/_layout/_auth/profile/_usuario/': typeof LayoutAuthProfileUsuarioIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/about'
    | '/'
    | '/profile'
    | '/dashboard'
    | '/profile/edit'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to: '' | '/about' | '/' | '/profile' | '/dashboard' | '/profile/edit'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_auth'
    | '/_layout/about'
    | '/_layout/'
    | '/_layout/_auth/profile'
    | '/_layout/_auth/profile/_usuario'
    | '/_layout/_auth/dashboard/'
    | '/_layout/_auth/profile/_usuario/edit'
    | '/_layout/_auth/profile/_usuario/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/_auth",
        "/_layout/about",
        "/_layout/"
      ]
    },
    "/_layout/_auth": {
      "filePath": "_layout._auth.tsx",
      "parent": "/_layout",
      "children": [
        "/_layout/_auth/profile",
        "/_layout/_auth/dashboard/"
      ]
    },
    "/_layout/about": {
      "filePath": "_layout.about.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout.index.tsx",
      "parent": "/_layout"
    },
    "/_layout/_auth/profile": {
      "filePath": "_layout._auth/profile",
      "parent": "/_layout/_auth",
      "children": [
        "/_layout/_auth/profile/_usuario"
      ]
    },
    "/_layout/_auth/profile/_usuario": {
      "filePath": "_layout._auth/profile/_usuario.tsx",
      "parent": "/_layout/_auth/profile",
      "children": [
        "/_layout/_auth/profile/_usuario/edit",
        "/_layout/_auth/profile/_usuario/"
      ]
    },
    "/_layout/_auth/dashboard/": {
      "filePath": "_layout._auth/dashboard/index.tsx",
      "parent": "/_layout/_auth"
    },
    "/_layout/_auth/profile/_usuario/edit": {
      "filePath": "_layout._auth/profile/_usuario/edit.tsx",
      "parent": "/_layout/_auth/profile/_usuario"
    },
    "/_layout/_auth/profile/_usuario/": {
      "filePath": "_layout._auth/profile/_usuario/index.tsx",
      "parent": "/_layout/_auth/profile/_usuario"
    }
  }
}
ROUTE_MANIFEST_END */
